### ISSUE TITLE
Unable to reach transmission web UI from remote host

### ISSUE THREAD

**Issue by wmene** [SebDanielsson/docker-wireguard-transmission#1]
Using this docker-compose.yaml and running on `host-a`
```
version: '3.3'
services:
    wireguard-transmission:
        container_name: wireguard-transmission
        privileged: true
        environment:
            - USERNAME=user
            - PASSWORD=pass
            - INTERFACE=my_vpn_service
              #- KILLSWITCH=wg0
        ports:
            - '51820:51820/udp'
            - '9091:9091'
        volumes:
            - '/path/to/wg-conf-dir:/etc/wireguard'
            - '/path/to/transmission-conf-dir:/etc/transmission-daemon'
            - '/path/to/transmission-complete-dir:/transmission/complete'
            - '/path/to/transmission-incomplete-dir:/transmission/incomplete'
            - '/path/to/transmission-watch-dir:/transmission/watch'
        image: sebdanielsson/wireguard-transmission                                                    
```

I am able to start this container and have it connect to my VPN service through wireguard.  From the same host that's running docker and this container, I can run 
```
host-a $> curl -L http://user:pass@localhost:9091
```
and get the UI html returned successfully.

However, I try to access the UI remotely from a host on the local network it just hangs:
```
host-b $> curl -L -v http://user:pass@host-a:9091
*   Trying 192.168.1.199...
* TCP_NODELAY set
...
```
I know port 9091 is accessible remotely because I have no issue reaching the web UI from a container running the `haugene/transmission-openvpn` image.  Any ideas?
