### ISSUE TITLE
settings.json not Updating from docker-compose Environment Variables

### ISSUE THREAD

**Issue by kennyparsons** [SebDanielsson/docker-wireguard-transmission#11]
Hello,

I am trying to run this container with some overrides in the settings.json. For example, in my docker-compose:
`TRANSMISSION_PEER_LIMIT_GLOBAL=10000`

But the settings.json shows:
`"peer-limit-global": 200,`

This is the default, so the entrypoint is not executing correctly. Here is the log from the container:
```
/usr/bin/wg-quick: line 32: ip6tables-restore: command not found,
[#] resolvconf -d wg0 -f,
[#] ip -6 rule delete table 51820,
[#] ip -6 rule delete table main suppress_prefixlength 0,
[#] ip link delete dev wg0,
Device "wg0" does not exist.,
Device "wg0" does not exist.,
Connecting to github.com (140.82.113.4:443),
Connecting to codeload.github.com (140.82.113.10:443),
saving to 'release.zip',
release.zip          100% |********************************| 1091k  0:00:00 ETA,
'release.zip' saved,
Archive:  release.zip,
   creating: combustion-release/,
  inflating: combustion-release/LICENSE,
  inflating: combustion-release/asset-manifest.json,
  inflating: combustion-release/favicon.ico,
  inflating: combustion-release/index.html,
  inflating: combustion-release/main.77f9cffc.css,
   creating: combustion-release/static/,
   creating: combustion-release/static/js/,
  inflating: combustion-release/static/js/main.9c210f2d.js,
   creating: combustion-release/static/media/,
  inflating: combustion-release/static/media/roboto-latin-100.3b8bb203.svg,
  inflating: combustion-release/static/media/roboto-latin-100.654cb4d3.woff,
  inflating: combustion-release/static/media/roboto-latin-100.8ce59883.woff2,
  inflating: combustion-release/static/media/roboto-latin-100.a2a3d1df.svg,
  inflating: combustion-release/static/media/roboto-latin-100.e2085b49.eot,
  inflating: combustion-release/static/media/roboto-latin-100italic.2058f87b.svg,
  inflating: combustion-release/static/media/roboto-latin-100italic.42de8983.woff,
  inflating: combustion-release/static/media/roboto-latin-100italic.4bec22c5.svg,
  inflating: combustion-release/static/media/roboto-latin-100italic.acee0ea9.woff2,
  inflating: combustion-release/static/media/roboto-latin-100italic.fafacae6.eot,
  inflating: combustion-release/static/media/roboto-latin-300.16ddb154.woff2,
  inflating: combustion-release/static/media/roboto-latin-300.1edaa6e5.svg,
  inflating: combustion-release/static/media/roboto-latin-300.c3547b2e.eot,
  inflating: combustion-release/static/media/roboto-latin-300.c69ee80f.svg,
  inflating: combustion-release/static/media/roboto-latin-300.ecce92d0.woff,
  inflating: combustion-release/static/media/roboto-latin-300italic.290e6a6c.svg,
  inflating: combustion-release/static/media/roboto-latin-300italic.2f1aacc1.eot,
  inflating: combustion-release/static/media/roboto-latin-300italic.3ddb7482.woff2,
  inflating: combustion-release/static/media/roboto-latin-300italic.4d08daeb.woff,
  inflating: combustion-release/static/media/roboto-latin-300italic.ab7ce49c.svg,
  inflating: combustion-release/static/media/roboto-latin-400.16e1d930.woff,
  inflating: combustion-release/static/media/roboto-latin-400.3d3a5358.svg,
  inflating: combustion-release/static/media/roboto-latin-400.7e367be0.woff2,
  inflating: combustion-release/static/media/roboto-latin-400.9f916e33.eot,
  inflating: combustion-release/static/media/roboto-latin-400.b7e5c110.svg,
  inflating: combustion-release/static/media/roboto-latin-400italic.13fb9544.svg,
  inflating: combustion-release/static/media/roboto-latin-400italic.16a42151.eot,
  inflating: combustion-release/static/media/roboto-latin-400italic.1e65e7e4.woff,
  inflating: combustion-release/static/media/roboto-latin-400italic.41135a79.svg,
  inflating: combustion-release/static/media/roboto-latin-400italic.984ae378.woff2,
  inflating: combustion-release/static/media/roboto-latin-500.2a52a20f.eot,
  inflating: combustion-release/static/media/roboto-latin-500.57af64fc.woff,
  inflating: combustion-release/static/media/roboto-latin-500.bb474f16.woff2,
  inflating: combustion-release/static/media/roboto-latin-500.cdadecea.svg,
  inflating: combustion-release/static/media/roboto-latin-500.f1d811cd.svg,
  inflating: combustion-release/static/media/roboto-latin-500italic.084d5c43.svg,
  inflating: combustion-release/static/media/roboto-latin-500italic.9e7beee5.woff2,
  inflating: combustion-release/static/media/roboto-latin-500italic.b518569d.svg,
  inflating: combustion-release/static/media/roboto-latin-500italic.b670694b.woff,
  inflating: combustion-release/static/media/roboto-latin-500italic.e50328c0.eot,
  inflating: combustion-release/static/media/roboto-latin-700.0d7e71f2.woff2,
  inflating: combustion-release/static/media/roboto-latin-700.128879da.eot,
  inflating: combustion-release/static/media/roboto-latin-700.525d5b45.woff,
  inflating: combustion-release/static/media/roboto-latin-700.7f57c4c0.svg,
  inflating: combustion-release/static/media/roboto-latin-700.e197191b.svg,
  inflating: combustion-release/static/media/roboto-latin-700italic.7176a9b5.svg,
  inflating: combustion-release/static/media/roboto-latin-700italic.7394ca9f.woff2,
  inflating: combustion-release/static/media/roboto-latin-700italic.96166ad6.eot,
  inflating: combustion-release/static/media/roboto-latin-700italic.ad0e74fc.woff,
  inflating: combustion-release/static/media/roboto-latin-700italic.bf39ef96.svg,
  inflating: combustion-release/static/media/roboto-latin-900.355550fa.eot,
  inflating: combustion-release/static/media/roboto-latin-900.5105ca25.svg,
  inflating: combustion-release/static/media/roboto-latin-900.de984c02.woff,
  inflating: combustion-release/static/media/roboto-latin-900.e43f0ef2.svg,
  inflating: combustion-release/static/media/roboto-latin-900.f4e8dc59.woff2,
  inflating: combustion-release/static/media/roboto-latin-900italic.258ac030.svg,
  inflating: combustion-release/static/media/roboto-latin-900italic.3b9590e0.woff,
  inflating: combustion-release/static/media/roboto-latin-900italic.4faec832.woff2,
  inflating: combustion-release/static/media/roboto-latin-900italic.822eba9c.eot,
  inflating: combustion-release/static/media/roboto-latin-900italic.9e3d8579.svg,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  154k  100  154k    0     0   665k      0 --:--:-- --:--:-- --:--:--  665k,
[2021-01-08 23:37:20.406] Transmission 3.00 (bb6b5a062e) started (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/session.c:769),
[2021-01-08 23:37:20.406] RPC Server Adding address to whitelist: 127.0.0.1 (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:956),
[2021-01-08 23:37:20.406] RPC Server Adding address to whitelist: ::1 (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:956),
[2021-01-08 23:37:20.406] RPC Server Serving RPC and Web requests on 0.0.0.0:9091/transmission/ (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:1243),
[2021-01-08 23:37:20.406] RPC Server Whitelist enabled (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/rpc-server.c:1249),
[2021-01-08 23:37:20.406] UDP Failed to set receive buffer: requested 4194304, got 425984 (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-udp.c:97),
[2021-01-08 23:37:20.406] UDP Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-udp.c:99),
[2021-01-08 23:37:20.406] UDP Failed to set send buffer: requested 1048576, got 425984 (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-udp.c:105),
[2021-01-08 23:37:20.406] UDP Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-udp.c:107),
[2021-01-08 23:37:20.406] DHT Generating new id (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/tr-dht.c:389),
[2021-01-08 23:37:20.406] Using settings from "/etc/transmission-daemon" (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:646),
[2021-01-08 23:37:20.406] Saved "/etc/transmission-daemon/settings.json" (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/variant.c:1221),
[2021-01-08 23:37:20.406] Port Forwarding (NAT-PMP) initnatpmp succeeded (0) (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/natpmp.c:73),
[2021-01-08 23:37:20.406] Port Forwarding (NAT-PMP) sendpublicaddressrequest succeeded (2) (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/natpmp.c:73),
```

Finally, here is my compose file:
```yaml
version: '3.7'
services:
  wireguard-transmission:
    container_name: wireguard-transmission
    image: sebdanielsson/wireguard-transmission
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - 'TRANSMISSION_RPC_WHITELIST=127.0.0.1,::1,192.168.*.*,172.30.0.0/16'
      - TRANSMISSION_RPC_WHITELIST_ENABLED=true
      - TRANSMISSION_RPC_PASSWORD=redacted
      - TRANSMISSION_RPC_USERNAME=kennyparsons
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=false
      - TRANSMISSION_PEER_LIMIT_GLOBAL=10000
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=100
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=0.00
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_SPEED_LIMIT_UP=0
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_WEB_UI=combustion
      - INTERFACE=wg0
      - KILLSWITCH=wg0
    ports:
      - '51820:51820/udp'
      - '9091:9091'
    volumes:
      - /mnt/nas-userdata/transmission/wg:/etc/wireguard
      - /mnt/nas-userdata/transmission/tr-01/daemon:/etc/transmission-daemon
      - /mnt/nas-userdata/transmission/tr-01/data:/data
      - /mnt/nas-userdata/transmission/tr-01/data/watch:/data/watch
      - /mnt/nas-userdata/transmission/tr-01/data/transmission-home:/data/transmission-home
      - /mnt/nas-userdata/transmission/tr-01/data/incomplete:/data/incomplete
      - /mnt/nas-userdata/transmission/tr-01/data/completed:/data/completed

```
